#
# data/Attributes.java
#
booleanTrueOption = Yes
booleanFalseOption = No
stdEmbedUnreadableTitle = Error Reading File
stdEmbedUnreadableMessage = This file can't be read.
stdEmbedParseErrorTitle = Error Parsing Content
stdEmbedParseErrorMessage = This file can't be parsed.
stdEmbedClickToLoad = (click to load)
stdEmbedContentInfo = (%s, %d bytes)
stdEmbedChooseNewOption = Choose New File
stdEmbedRemoveOption = Remove File
stdEmbedEmbedOption = Embed in Project
stdEmbedLinkOption = Link to File
stdEmbedCancelOption = Cancel
stdEmbedStorageDialogQuestion = This content is %d bytes. How should it be stored?
stdEmbedStorageDialogTitle = Image Storage
#
# data/Direction.java
#
directionEastOption = East
directionWestOption = West
directionNorthOption = North
directionSouthOption = South
directionNorthVertical = Top
directionSouthVertical = Bottom
directionEastVertical = Right
directionWestVertical = Left
#
# data/Value.java
#
valueErrorSymbol = E
valueUnknownSymbol = z
valueError = Error
valueUnknown = Floating
