#
# BoardEditor
#
XMLFileFilter = XML Files
PNGFileFilter = PNG Images
FPGABoardEditor = FPGA Board Editor
FPGACommander = FPGA Synthesis & Download
FPGASettings = Toolchain Settings
boardEditorUnsavedTitle = Unsaved Board
boardEditorUnsavedMessage = What should happen to your unsaved FPGA board?
boardEditorSaveOption = Save
boardEditorDiscardOption = Discard
boardEditorCancelOption = Cancel
