#
# OptionsActions.java
#
setOptionAction = Set %s
addMouseMappingAction = Add Mouse Mapping
removeMouseMappingAction = Remove Mouse Mapping
#
# SimulateOptions.java
#
simulateTitle = Simulation
simulateHelp = Configure the engine for simulating circuit behavior.
simulateLimit = Iterations until oscillation
gateUndefined = Unconnected gate inputs
simulateRandomness = Add noise to component delays
simulateSmoothing = Enable frequency smoothing
mainTick = Duration of main tick (F2) 
#
# MouseOptions.java
#
mouseTitle = Mouse
mouseHelp = Configure how Logisim responds to mouse clicks.
mouseInstruction = Configure how Logisim responds to mouse clicks.
mouseColumnTrigger = On this trigger \u2026
mouseColumnAction = \u2026 perform this action
mouseAddButton = Add new mapping
mouseResetButton = Reset to defaults
mouseEditButton = Edit
mouseRemoveButton = Remove
mouseResetTitle = Reset Mappings
mouseResetConfirm = This will clear all mouse mappings and restore defaults. Continue?
mouseDialogAddTitle = Add Mouse Mapping
mouseDialogEditTitle = Edit Mouse Mapping
mouseDialogAdd = Add
mouseDialogSave = Save
mouseDialogCancel = Cancel
mouseButtonLabel = Mouse button:
mouseUnavailableLabel = %s (often unavailable on MacOS)
mouseModLabel = Modifiers:
mouseToolAttrsLabel = Component properties:
mouseAddTool = Place %s
#
# ToolbarOptions.java
#
toolbarTitle = Toolbar
toolbarHelp = Edit tools appearing in toolbar.
toolbarAvailableItems = Available Items
toolbarCurrentItems = Current Toolbar
toolbarExplanation = Edit project toolbar by rearranging or dragging items into or out of the list at right.
toolbarAddTool = Add Item
toolbarAddSeparator = Add Separator
toolbarMoveUp = Move Up
toolbarMoveDown = Move Down
toolbarRemove = Remove Item
#
# ToolbarActions.java
#
toolbarAddAction = Add Toolbar Button
toolbarRemoveAction = Remove Toolbar Button
toolbarMoveAction = Move Toolbar Button
toolbarInsertSepAction = Insert Separator
toolbarRemoveSepAction = Remove Separator
