#
# util/FontUtil.java
#
fontPlainStyle = Plain
fontBoldStyle = Bold
fontItalicStyle = Italic
fontBoldItalicStyle = Bold Italic
#
# util/InputEventUtil.java
#
metaKeyMacOS = \u2318
altKeyMacOS = \u2325
ctrlKeyMacOS = \u2303
shiftKeyMacOS = \u21E7
metaModMacOS = Command (\u2318)
altModMacOS = Option (\u2325)
ctrlModMacOS = Control (\u2303)
shiftModMacOS = Shift (\u21E7)
button1MacOS = Click
button2MacOS = Middle Click
button3MacOS = Two-finger Click

metaKeyWindows = Win
altKeyWindows = Alt
ctrlKeyWindows = Ctrl
shiftKeyWindows = Shift
metaModWindows = Windows Key
altModWindows = Alt
ctrlModWindows = Control
shiftModWindows = Shift
button1Windows = Left-Click
button2Windows = Middle-Click
button3Windows = Right-Click

metaKeyLinux = Meta
altKeyLinux = Alt
ctrlKeyLinux = Ctrl
shiftKeyLinux = Shift
metaModLinux = Meta
altModLinux = Alt
ctrlModLinux = Control
shiftModLinux = Shift
button1Linux = Left-Click
button2Linux = Middle-Click
button3Linux = Right-Click

#
# util/JDialogOk.java
#
dlogOkButton = OK
dlogCancelButton = Cancel
#
# util/LocaleManager.java
#
# If the user selects to "replace accented characters" in the International
# dialog, the program will replace accented characters based on
# the slash-delimited character-string pairs in accentReplacements.
# For example, with German, accentReplacements might be
# "\u00f6 oe/\u00d6 Oe/\u00fc ue/\u00dc ue/\u00df ss" so that umlauted o's and u's are
# replaced, as would be essets.
accentReplacements =
#
# util/WindowMenu.java
#
windowMenu = Window
windowMinimizeItem = Minimize
windowZoomItem = Maximize
windowZoomItemMac = Zoom
windowCloseItem = Close
windowShowToolbarItem = Show Toolbar
#
# Questa HDL Validation
#
questaDialogTitle = Select Questa Advanced Simulator
questaDialogButton = Select
questaErrorTitle = Error setting directory
questaErrorMessage = Questa Advanced Simulator could not be found in the specified directory
questaIoErrorMessage = An error occured while retrieving the path
questaLibraryErrorTitle = Library error
questaLibraryErrorMessage = Could not create library work:
questaValidationFailedTitle = Validation failed
questaValidationFailedMessage = One or more errors detected:
questaValidationAbordedTitle = The validation process of the VHDL component was aborded
questaValidationAbordedMessage = The validation process of the VHDL component was aborded
questaValidationIoException = An I/O error occured during the validation
questaValidationInterrupted = An internal error occured during the validation

dateFormat = dd.MM.yy HH:mm:ss

desktopFallbackOpenBrowserTitle = Launching Browser...
desktopFallbackOpenBrowserMessage = If browser doesn't open, please try this instead:
desktopFallbackOpenBrowserFailed = Oops, browser won't open. Please try this instead:
desktopFallbackOpenMailTitle = Launching Mail...
desktopFallbackOpenMailMessage = If email doesn't open, please try this instead:
desktopFallbackOpenMailFailed = Oops, email won't open. Please try this instead:
desktopFallbackOpenFolderTitle = Opening Folder...
desktopFallbackOpenFolderMessage = If the folder doesn't open, please try this instead:
desktopFallbackOpenFolderFailed = Oops, the folder won't open. Please try this instead:
desktopFallbackOpenFileTitle = Opening File...
desktopFallbackOpenFileMessage = If the file doesn't open, please try this instead:
desktopFallbackOpenFileFailed = Oops, the file won't open. Please try this instead:
desktopFallbackCopy = Copy
desktopFallbackDismiss = Copy
